printWidth: 80
tabWidth: 2
useTabs: true
semi: false
singleQuote: true
quoteProps: consistent
jsxSingleQuote: false
trailingComma: es5
bracketSpacing: true
bracketSameLine: false
arrowParens: always
endOfLine: lf
