version: "3"

# https://docs.docker.com/compose/compose-file/compose-file-v3/#extension-fields
x-lit-wc-dist-volume:
  &lit-wc-dist-volume
  type: bind
  source: ./packages/lit-wc/dist
  target: /app/packages/lit-wc/dist

x-lit-wc-type-volume:
  &lit-wc-types-volume
  type: bind
  source: ./packages/lit-wc/types
  target: /app/packages/lit-wc/types

services:
  home:
    build:
      context: .
      dockerfile: ./apps/home/Dockerfile.dev
    command: yarn dev --filter=home
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    volumes:
      - *lit-wc-dist-volume
      - *lit-wc-types-volume
      - ./apps/home/src:/app/apps/home/src
      - ./apps/home/public:/app/apps/home/public

  about:
    build:
      context: .
      dockerfile: ./apps/about/Dockerfile.dev
    command: yarn dev --filter=about
    stdin_open: true
    tty: true
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
    volumes:
      - *lit-wc-dist-volume
      - *lit-wc-types-volume
      - ./apps/about/src:/app/apps/about/src
      - ./apps/about/public:/app/apps/about/public

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile.dev
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/conf.d/nginx.conf
