version: "3.9"

services:
  strapi:
    env_file:
      - ./.envs/strapi/.env.production
    environment:
      DATABASE_HOST: "strapi_db"
    depends_on:
      strapi_db:
        condition: service_healthy
    networks:
      - multi-app-db-network

  strapi_db:
    image: postgres:15.1-alpine
    container_name: multi-app-strapi-db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready --username=strapidbuser --dbname=strapidb" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    env_file:
      - ./.envs/strapi/.env.production
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
    volumes:
      - postgres_strapi:/var/lib/postgresql/data
    networks:
      - multi-app-db-network

volumes:
  postgres_strapi:

networks:
  multi-app-db-network:
    driver: bridge
