version: "3.9"

# https://docs.docker.com/compose/compose-file/compose-file-v3/#extension-fields
x-lit-wc-dist-volume:
  &lit-wc-dist-volume
  type: bind
  source: ./packages/lit-wc/dist
  target: /app/packages/lit-wc/dist

x-lit-wc-type-volume:
  &lit-wc-types-volume
  type: bind
  source: ./packages/lit-wc/types
  target: /app/packages/lit-wc/types

x-svelte-wc-dist-volume:
  &svelte-wc-dist-volume
  type: bind
  source: ./packages/svelte-wc/dist
  target: /app/packages/svelte-wc/dist

x-svelte-wc-type-volume:
  &svelte-wc-types-volume
  type: bind
  source: ./packages/svelte-wc/types
  target: /app/packages/svelte-wc/types

services:
  home:
    build:
      context: .
      dockerfile: ./apps/home/Dockerfile.dev
    command: yarn dev --filter=home
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    volumes:
      - *lit-wc-dist-volume
      - *lit-wc-types-volume
      - *svelte-wc-dist-volume
      - *svelte-wc-types-volume
      - ./apps/home/src:/app/apps/home/src
      - ./apps/home/public:/app/apps/home/public

  about:
    build:
      context: .
      dockerfile: ./apps/about/Dockerfile.dev
    command: yarn dev --filter=about
    stdin_open: true
    tty: true
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
    volumes:
      - *lit-wc-dist-volume
      - *lit-wc-types-volume
      - *svelte-wc-dist-volume
      - *svelte-wc-types-volume
      - ./apps/about/src:/app/apps/about/src
      - ./apps/about/public:/app/apps/about/public

  chat:
    build:
      context: .
      dockerfile: ./apps/chat/Dockerfile.dev
    command: yarn dev --filter=chat
    stdin_open: true
    tty: true
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
    volumes:
      - ./apps/chat/src:/app/apps/chat/src
      - ./apps/chat/public:/app/apps/chat/public

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile.dev
    depends_on:
      - strapi
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/conf.d/nginx.conf

  strapi:
    build:
      context: .
      dockerfile: apps/strapi/Dockerfile.dev
    container_name: multi-app-strapi
    ports:
      - '1337:1337'
    restart: on-failure
    env_file:
      - ./.envs/strapi/.env.development
    volumes:
      - ./apps/strapi/.tmp:/app/.tmp
      - ./apps/strapi/config:/app/config
      - ./apps/strapi/database:/app/config
      - ./apps/strapi/public/uploads:/app/public/uploads
      - ./apps/strapi/src:/app/src
      - ./apps/strapi/.env:/app/.env
      - ./apps/strapi/tsconfig.json:/app/tsconfig.json
    networks:
      - multi-app-network
