FROM node:18.12.0-alpine

RUN apk add --no-cache libc6-compat
RUN apk update

WORKDIR /app

RUN yarn global add turbo

COPY package.json yarn.lock ./
COPY configs ./configs
COPY apps/about/package.json ./apps/about/package.json

COPY packages/lit-wc/package.json ./packages/lit-wc/package.json
COPY packages/global-css/package.json ./packages/global-css/package.json

RUN yarn install

COPY . .


